FLAT:003FFFFF ;
FLAT:003FFFFF ; +-------------------------------------------------------------------------+
FLAT:003FFFFF ; |      This file was generated by The Interactive Disassembler (IDA)      |
FLAT:003FFFFF ; |           Copyright (c) 2021 Hex-Rays, <support@hex-rays.com>           |
FLAT:003FFFFF ; |                            Freeware version                             |
FLAT:003FFFFF ; +-------------------------------------------------------------------------+
FLAT:003FFFFF ;
FLAT:003FFFFF ; Input SHA256 : 0C7CDFDB6D4C8876E9C5BAE906FCF1CBF174F019EF45D518954885856501A0BE
FLAT:003FFFFF ; Input MD5    : 66F573036F8B99863D75743EFF84F15D
FLAT:003FFFFF ; Input CRC32  : 503D64C9
FLAT:003FFFFF
FLAT:003FFFFF
FLAT:003FFFFF                 .686p
FLAT:003FFFFF                 .mmx
FLAT:003FFFFF                 .model flat
FLAT:003FFFFF
FLAT:003FFFFF ; ===========================================================================
FLAT:003FFFFF
FLAT:003FFFFF ; Segment type: Group
FLAT:003FFFFF
CODE:00401000 ; File Name   : C:\Users\dns\Downloads\crackme.exe
CODE:00401000 ; Format      : Portable executable for 80386 (PE)
CODE:00401000 ; Imagebase   : 400000
CODE:00401000 ; Timestamp   : 0AD92429 (Wed Oct 08 12:18:49 1975)
CODE:00401000 ; Section 1. (virtual address 00001000)
CODE:00401000 ; Virtual size                  : 00001000 (   4096.)
CODE:00401000 ; Section size in file          : 00000600 (   1536.)
CODE:00401000 ; Offset to raw data for section: 00000600
CODE:00401000 ; Flags 60000020: Text Executable Readable
CODE:00401000 ; Alignment     : default
CODE:00401000 ; ===========================================================================
CODE:00401000
CODE:00401000 ; Segment type: Pure code
CODE:00401000 ; Segment permissions: Read/Execute
CODE:00401000 CODE            segment para public 'CODE' use32
CODE:00401000                 assume cs:CODE
CODE:00401000                 ;org 401000h
CODE:00401000                 assume es:FLAT, ss:FLAT, ds:CODE, fs:nothing, gs:nothing
CODE:00401000
CODE:00401000 ; =============== S U B R O U T I N E =======================================
CODE:00401000
CODE:00401000
CODE:00401000                 public start
CODE:00401000 start           proc near
CODE:00401000                 push    0
CODE:00401002                 call    GetModuleHandleA
CODE:00401007                 mov     ds:dword_4020CA, eax
CODE:0040100C                 push    0
CODE:0040100E                 push    offset aNoNeedToDisasm ; "No need to disasm the code!"
CODE:00401013                 call    FindWindowA
CODE:00401018                 or      eax, eax
CODE:0040101A                 jz      short loc_40101D
CODE:0040101C                 retn
CODE:0040101D ; ---------------------------------------------------------------------------
CODE:0040101D
CODE:0040101D loc_40101D:                             ; CODE XREF: start+1A↑j
CODE:0040101D                 mov     ds:dword_402064, 4003h
CODE:00401027                 mov     ds:dword_402068, offset WndProc
CODE:00401031                 mov     ds:dword_40206C, 0
CODE:0040103B                 mov     ds:dword_402070, 0
CODE:00401045                 mov     eax, ds:dword_4020CA
CODE:0040104A                 mov     ds:dword_402074, eax
CODE:0040104F                 push    64h ; 'd'
CODE:00401051                 push    eax
CODE:00401052                 call    LoadIconA
CODE:00401057                 mov     ds:dword_402078, eax
CODE:0040105C                 push    7F00h
CODE:00401061                 push    0
CODE:00401063                 call    LoadCursorA
CODE:00401068                 mov     ds:dword_40207C, eax
CODE:0040106D                 mov     ds:dword_402080, 5
CODE:00401077                 mov     ds:dword_402084, offset aMenu ; "MENU"
CODE:00401081                 mov     ds:dword_402088, offset aNoNeedToDisasm ; "No need to disasm the code!"
CODE:0040108B                 push    offset dword_402064
CODE:00401090                 call    RegisterClassA
CODE:00401095                 push    0
CODE:00401097                 push    ds:dword_4020CA
CODE:0040109D                 push    0
CODE:0040109F                 push    0
CODE:004010A1                 push    8000h
CODE:004010A6                 push    8000h
CODE:004010AB                 push    6Eh ; 'n'
CODE:004010AD                 push    0B4h ; '´'
CODE:004010B2                 push    0CF0000h
CODE:004010B7                 push    offset aCrackmeV10 ; "CrackMe v1.0"
CODE:004010BC                 push    offset aNoNeedToDisasm ; "No need to disasm the code!"
CODE:004010C1                 push    0
CODE:004010C3                 call    CreateWindowExA
CODE:004010C8                 mov     ds:dword_402004, eax
CODE:004010CD                 push    1
CODE:004010CF                 push    ds:dword_402004
CODE:004010D5                 call    ShowWindow
CODE:004010DA                 push    ds:dword_402004
CODE:004010E0                 call    UpdateWindow
CODE:004010E5                 push    1
CODE:004010E7                 push    0
CODE:004010E9                 push    dword ptr [ebp+8]
CODE:004010EC                 call    InvalidateRect
CODE:004010F1
CODE:004010F1 loc_4010F1:                             ; CODE XREF: start+11B↓j
CODE:004010F1                 push    0
CODE:004010F3                 push    0
CODE:004010F5                 push    0
CODE:004010F7                 push    offset unk_402048
CODE:004010FC                 call    GetMessageA
CODE:00401101                 cmp     ax, 0
CODE:00401105                 jz      short loc_40111D
CODE:00401107                 push    offset unk_402048
CODE:0040110C                 call    TranslateMessage
CODE:00401111                 push    offset unk_402048
CODE:00401116                 call    DispatchMessageA
CODE:0040111B                 jmp     short loc_4010F1
CODE:0040111D ; ---------------------------------------------------------------------------
CODE:0040111D
CODE:0040111D loc_40111D:                             ; CODE XREF: start+105↑j
CODE:0040111D                 push    ds:dword_402050
CODE:00401123                 call    ExitProcess
CODE:00401123 start           endp ; sp-analysis failed
CODE:00401123
CODE:00401128 ; Exported entry   1. WndProc
CODE:00401128
CODE:00401128 ; =============== S U B R O U T I N E =======================================
CODE:00401128
CODE:00401128 ; Attributes: bp-based frame
CODE:00401128
CODE:00401128                 public WndProc
CODE:00401128 WndProc         proc near               ; DATA XREF: start+27↑o
CODE:00401128
CODE:00401128 arg_0           = dword ptr  8
CODE:00401128 arg_4           = dword ptr  0Ch
CODE:00401128 arg_8           = dword ptr  10h
CODE:00401128 arg_C           = dword ptr  14h
CODE:00401128
CODE:00401128                 enter   0, 0
CODE:0040112C                 push    esi
CODE:0040112D                 push    edi
CODE:0040112E                 push    ebx
CODE:0040112F                 cmp     [ebp+arg_4], 2
CODE:00401133                 jz      short loc_401193
CODE:00401135                 cmp     [ebp+arg_4], 204h
CODE:0040113C                 jz      short loc_4011A3
CODE:0040113E                 nop
CODE:0040113F                 nop
CODE:00401140                 nop
CODE:00401141                 nop
CODE:00401142                 cmp     [ebp+arg_4], 5
CODE:00401146                 jz      short loc_4011A5
CODE:00401148                 cmp     [ebp+arg_4], 1
CODE:0040114C                 jz      short loc_401176
CODE:0040114E                 cmp     [ebp+arg_4], 201h
CODE:00401155                 jz      short loc_4011A1
CODE:00401157                 cmp     [ebp+arg_4], 24h ; '$'
CODE:0040115B                 jz      short loc_4011AC
CODE:0040115D                 cmp     [ebp+arg_4], 111h
CODE:00401164                 jz      short loc_4011D2
CODE:00401166                 nop
CODE:00401167                 nop
CODE:00401168                 nop
CODE:00401169                 nop
CODE:0040116A                 jmp     short loc_401180
CODE:0040116C ; ---------------------------------------------------------------------------
CODE:0040116C                 mov     eax, 0
CODE:00401171                 jmp     short loc_4011E6
CODE:00401171 ; ---------------------------------------------------------------------------
CODE:00401173                 db 3 dup(90h)
CODE:00401176 ; ---------------------------------------------------------------------------
CODE:00401176
CODE:00401176 loc_401176:                             ; CODE XREF: WndProc+24↑j
CODE:00401176                 mov     eax, 0
CODE:0040117B                 jmp     short loc_4011E6
CODE:0040117B ; ---------------------------------------------------------------------------
CODE:0040117D                 align 10h
CODE:00401180
CODE:00401180 loc_401180:                             ; CODE XREF: WndProc+42↑j
CODE:00401180                 push    [ebp+arg_C]
CODE:00401183                 push    [ebp+arg_8]
CODE:00401186                 push    [ebp+arg_4]
CODE:00401189                 push    [ebp+arg_0]
CODE:0040118C                 call    DefWindowProcA
CODE:00401191                 jmp     short loc_4011E6
CODE:00401193 ; ---------------------------------------------------------------------------
CODE:00401193
CODE:00401193 loc_401193:                             ; CODE XREF: WndProc+B↑j
CODE:00401193                                         ; WndProc+B4↓j
CODE:00401193                 push    0
CODE:00401195                 call    PostQuitMessage
CODE:0040119A                 mov     eax, 0
CODE:0040119F                 jmp     short loc_4011E6
CODE:004011A1 ; ---------------------------------------------------------------------------
CODE:004011A1
CODE:004011A1 loc_4011A1:                             ; CODE XREF: WndProc+2D↑j
CODE:004011A1                 jmp     short loc_4011E6
CODE:004011A3 ; ---------------------------------------------------------------------------
CODE:004011A3
CODE:004011A3 loc_4011A3:                             ; CODE XREF: WndProc+14↑j
CODE:004011A3                 jmp     short loc_4011E6
CODE:004011A5 ; ---------------------------------------------------------------------------
CODE:004011A5
CODE:004011A5 loc_4011A5:                             ; CODE XREF: WndProc+1E↑j
CODE:004011A5                 mov     eax, 0
CODE:004011AA                 jmp     short loc_4011E6
CODE:004011AC ; ---------------------------------------------------------------------------
CODE:004011AC
CODE:004011AC loc_4011AC:                             ; CODE XREF: WndProc+33↑j
CODE:004011AC                 mov     ebx, [ebp+arg_C]
CODE:004011AF                 mov     dword ptr [ebx+18h], 118h
CODE:004011B6                 mov     dword ptr [ebx+1Ch], 0A0h ; ' '
CODE:004011BD                 mov     dword ptr [ebx+20h], 118h
CODE:004011C4                 mov     dword ptr [ebx+24h], 0A0h ; ' '
CODE:004011CB                 mov     eax, 0
CODE:004011D0                 jmp     short loc_4011E6
CODE:004011D2 ; ---------------------------------------------------------------------------
CODE:004011D2
CODE:004011D2 loc_4011D2:                             ; CODE XREF: WndProc+3C↑j
CODE:004011D2                 cmp     [ebp+arg_8], 67h ; 'g'
CODE:004011D6                 jz      short loc_4011ED
CODE:004011D8                 cmp     [ebp+arg_8], 65h ; 'e'
CODE:004011DC                 jz      short loc_401193
CODE:004011DE                 cmp     [ebp+arg_8], 66h ; 'f'
CODE:004011E2                 jz      short loc_401209
CODE:004011E4                 jmp     short $+2
CODE:004011E6 ; ---------------------------------------------------------------------------
CODE:004011E6
CODE:004011E6 loc_4011E6:                             ; CODE XREF: WndProc+49↑j
CODE:004011E6                                         ; WndProc+53↑j ...
CODE:004011E6                 pop     ebx
CODE:004011E7                 pop     edi
CODE:004011E8                 pop     esi
CODE:004011E9                 leave
CODE:004011EA                 retn    10h
CODE:004011ED ; ---------------------------------------------------------------------------
CODE:004011ED
CODE:004011ED loc_4011ED:                             ; CODE XREF: WndProc+AE↑j
CODE:004011ED                 push    0
CODE:004011EF                 push    offset sub_40130A
CODE:004011F4                 push    [ebp+arg_0]
CODE:004011F7                 push    offset aDlgAbout ; "DLG_ABOUT"
CODE:004011FC                 push    ds:dword_4020CA
CODE:00401202                 call    DialogBoxParamA
CODE:00401207                 jmp     short loc_4011E6
CODE:00401209 ; ---------------------------------------------------------------------------
CODE:00401209
CODE:00401209 loc_401209:                             ; CODE XREF: WndProc+BA↑j
CODE:00401209                 push    0
CODE:0040120B                 push    offset sub_401253
CODE:00401210                 push    [ebp+arg_0]
CODE:00401213                 push    offset aDlgRegis ; "DLG_REGIS"
CODE:00401218                 push    ds:dword_4020CA
CODE:0040121E                 call    DialogBoxParamA
CODE:00401223                 cmp     eax, 0
CODE:00401226                 jz      short loc_4011E6
CODE:00401228                 push    offset unk_40218E
CODE:0040122D                 call    sub_40137E
CODE:00401232                 push    eax
CODE:00401233                 push    offset unk_40217E
CODE:00401238                 call    sub_4013D8
CODE:0040123D                 add     esp, 4
CODE:00401240                 pop     eax
CODE:00401241                 cmp     eax, ebx
CODE:00401243                 jz      short loc_40124C
CODE:00401245                 call    sub_401362
CODE:0040124A                 jmp     short loc_4011E6
CODE:0040124C ; ---------------------------------------------------------------------------
CODE:0040124C
CODE:0040124C loc_40124C:                             ; CODE XREF: WndProc+11B↑j
CODE:0040124C                 call    sub_40134D
CODE:00401251                 jmp     short loc_4011E6
CODE:00401251 WndProc         endp
CODE:00401251
CODE:00401253
CODE:00401253 ; =============== S U B R O U T I N E =======================================
CODE:00401253
CODE:00401253 ; Attributes: bp-based frame
CODE:00401253
CODE:00401253 sub_401253      proc near               ; DATA XREF: WndProc+E3↑o
CODE:00401253
CODE:00401253 arg_0           = dword ptr  8
CODE:00401253 arg_4           = dword ptr  0Ch
CODE:00401253 arg_8           = dword ptr  10h
CODE:00401253
CODE:00401253                 enter   0, 0
CODE:00401257                 push    ebx
CODE:00401258                 push    esi
CODE:00401259                 push    edi
CODE:0040125A                 cmp     [ebp+arg_4], 110h
CODE:00401261                 jz      short loc_401297
CODE:00401263                 cmp     [ebp+arg_4], 111h
CODE:0040126A                 jz      short loc_4012A1
CODE:0040126C                 cmp     [ebp+arg_4], 10h
CODE:00401270                 jz      loc_4012F7
CODE:00401276                 cmp     [ebp+arg_4], 201h
CODE:0040127D                 jz      short loc_40128B
CODE:0040127F                 mov     eax, 0
CODE:00401284
CODE:00401284 loc_401284:                             ; CODE XREF: sub_401253+4C↓j
CODE:00401284                                         ; sub_401253+A2↓j ...
CODE:00401284                 pop     edi
CODE:00401285                 pop     esi
CODE:00401286                 pop     ebx
CODE:00401287                 leave
CODE:00401288                 retn    10h
CODE:0040128B ; ---------------------------------------------------------------------------
CODE:0040128B
CODE:0040128B loc_40128B:                             ; CODE XREF: sub_401253+2A↑j
CODE:0040128B                 push    1
CODE:0040128D                 push    0
CODE:0040128F                 push    [ebp+arg_0]
CODE:00401292                 call    InvalidateRect
CODE:00401297
CODE:00401297 loc_401297:                             ; CODE XREF: sub_401253+E↑j
CODE:00401297                 push    [ebp+arg_0]
CODE:0040129A                 call    SetFocus
CODE:0040129F                 jmp     short loc_401284
CODE:004012A1 ; ---------------------------------------------------------------------------
CODE:004012A1
CODE:004012A1 loc_4012A1:                             ; CODE XREF: sub_401253+17↑j
CODE:004012A1                                         ; sub_401253+80↓j
CODE:004012A1                 xor     eax, eax
CODE:004012A3                 cmp     [ebp+arg_8], 3EBh
CODE:004012AA                 jz      short loc_4012F7
CODE:004012AC                 cmp     [ebp+arg_8], 3EAh
CODE:004012B3                 jnz     short loc_4012F0
CODE:004012B5                 push    0Bh
CODE:004012B7                 push    offset unk_40218E
CODE:004012BC                 push    3E8h
CODE:004012C1                 push    [ebp+arg_0]
CODE:004012C4                 call    GetDlgItemTextA
CODE:004012C9                 cmp     eax, 1
CODE:004012CC                 mov     [ebp+arg_8], 3EBh
CODE:004012D3                 jb      short loc_4012A1
CODE:004012D5                 push    0Bh
CODE:004012D7                 push    offset unk_40217E
CODE:004012DC                 push    3E9h
CODE:004012E1                 push    [ebp+arg_0]
CODE:004012E4                 call    GetDlgItemTextA
CODE:004012E9                 mov     eax, 1
CODE:004012EE                 jmp     short loc_4012F7
CODE:004012F0 ; ---------------------------------------------------------------------------
CODE:004012F0
CODE:004012F0 loc_4012F0:                             ; CODE XREF: sub_401253+60↑j
CODE:004012F0                 mov     eax, 0
CODE:004012F5                 jmp     short loc_401284
CODE:004012F7 ; ---------------------------------------------------------------------------
CODE:004012F7
CODE:004012F7 loc_4012F7:                             ; CODE XREF: sub_401253+1D↑j
CODE:004012F7                                         ; sub_401253+57↑j ...
CODE:004012F7                 push    eax
CODE:004012F8                 push    [ebp+arg_0]
CODE:004012FB                 call    EndDialog
CODE:00401300                 mov     eax, 1
CODE:00401305                 jmp     loc_401284
CODE:00401305 sub_401253      endp
CODE:00401305
CODE:0040130A
CODE:0040130A ; =============== S U B R O U T I N E =======================================
CODE:0040130A
CODE:0040130A ; Attributes: bp-based frame
CODE:0040130A
CODE:0040130A sub_40130A      proc near               ; DATA XREF: WndProc+C7↑o
CODE:0040130A
CODE:0040130A arg_0           = dword ptr  8
CODE:0040130A arg_4           = dword ptr  0Ch
CODE:0040130A arg_8           = dword ptr  10h
CODE:0040130A
CODE:0040130A                 enter   0, 0
CODE:0040130E                 push    ebx
CODE:0040130F                 push    esi
CODE:00401310                 push    edi
CODE:00401311                 cmp     [ebp+arg_4], 111h
CODE:00401318                 jz      short loc_40132C
CODE:0040131A                 cmp     [ebp+arg_4], 10h
CODE:0040131E                 jz      short loc_401335
CODE:00401320                 mov     eax, 0
CODE:00401325
CODE:00401325 loc_401325:                             ; CODE XREF: sub_40130A+3A↓j
CODE:00401325                                         ; sub_40130A+41↓j
CODE:00401325                 pop     edi
CODE:00401326                 pop     esi
CODE:00401327                 pop     ebx
CODE:00401328                 leave
CODE:00401329                 retn    10h
CODE:0040132C ; ---------------------------------------------------------------------------
CODE:0040132C
CODE:0040132C loc_40132C:                             ; CODE XREF: sub_40130A+E↑j
CODE:0040132C                 cmp     [ebp+arg_8], 3F2h
CODE:00401333                 jnz     short loc_401346
CODE:00401335
CODE:00401335 loc_401335:                             ; CODE XREF: sub_40130A+14↑j
CODE:00401335                 push    0
CODE:00401337                 push    [ebp+arg_0]
CODE:0040133A                 call    EndDialog
CODE:0040133F                 mov     eax, 1
CODE:00401344                 jmp     short loc_401325
CODE:00401346 ; ---------------------------------------------------------------------------
CODE:00401346
CODE:00401346 loc_401346:                             ; CODE XREF: sub_40130A+29↑j
CODE:00401346                 mov     eax, 0
CODE:0040134B                 jmp     short loc_401325
CODE:0040134B sub_40130A      endp
CODE:0040134B
CODE:0040134D
CODE:0040134D ; =============== S U B R O U T I N E =======================================
CODE:0040134D
CODE:0040134D
CODE:0040134D sub_40134D      proc near               ; CODE XREF: WndProc:loc_40124C↑p
CODE:0040134D                 push    30h ; '0'
CODE:0040134F                 push    offset aGoodWork ; "Good work!"
CODE:00401354                 push    offset aGreatWorkMateN ; "Great work, mate!\rNow try the next Cra"...
CODE:00401359                 push    dword ptr [ebp+8]
CODE:0040135C                 call    MessageBoxA
CODE:00401361                 retn
CODE:00401361 sub_40134D      endp
CODE:00401361
CODE:00401362
CODE:00401362 ; =============== S U B R O U T I N E =======================================
CODE:00401362
CODE:00401362
CODE:00401362 sub_401362      proc near               ; CODE XREF: WndProc+11D↑p
CODE:00401362                 push    0
CODE:00401364                 call    MessageBeep
CODE:00401369                 push    30h ; '0'
CODE:0040136B                 push    offset aNoLuck  ; "No luck!"
CODE:00401370                 push    offset aNoLuckThereMat ; "No luck there, mate!"
CODE:00401375                 push    dword ptr [ebp+8]
CODE:00401378                 call    MessageBoxA
CODE:0040137D                 retn
CODE:0040137D sub_401362      endp
CODE:0040137D
CODE:0040137E
CODE:0040137E ; =============== S U B R O U T I N E =======================================
CODE:0040137E
CODE:0040137E
CODE:0040137E sub_40137E      proc near               ; CODE XREF: WndProc+105↑p
CODE:0040137E
CODE:0040137E arg_0           = dword ptr  4
CODE:0040137E
CODE:0040137E                 mov     esi, [esp+arg_0]
CODE:00401382                 push    esi
CODE:00401383
CODE:00401383 loc_401383:                             ; CODE XREF: sub_40137E+14↓j
CODE:00401383                                         ; sub_40137E+1C↓j
CODE:00401383                 mov     al, [esi]
CODE:00401385                 test    al, al
CODE:00401387                 jz      short loc_40139C
CODE:00401389                 cmp     al, 41h ; 'A'
CODE:0040138B                 jb      short loc_4013AC
CODE:0040138D                 cmp     al, 5Ah ; 'Z'
CODE:0040138F                 jnb     short loc_401394
CODE:00401391                 inc     esi
CODE:00401392                 jmp     short loc_401383
CODE:00401394 ; ---------------------------------------------------------------------------
CODE:00401394
CODE:00401394 loc_401394:                             ; CODE XREF: sub_40137E+11↑j
CODE:00401394                 call    sub_4013D2
CODE:00401399                 inc     esi
CODE:0040139A                 jmp     short loc_401383
CODE:0040139C ; ---------------------------------------------------------------------------
CODE:0040139C
CODE:0040139C loc_40139C:                             ; CODE XREF: sub_40137E+9↑j
CODE:0040139C                 pop     esi
CODE:0040139D                 call    sub_4013C2
CODE:004013A2                 xor     edi, 5678h
CODE:004013A8                 mov     eax, edi
CODE:004013AA                 jmp     short locret_4013C1
CODE:004013AC ; ---------------------------------------------------------------------------
CODE:004013AC
CODE:004013AC loc_4013AC:                             ; CODE XREF: sub_40137E+D↑j
CODE:004013AC                 pop     esi
CODE:004013AD                 push    30h ; '0'
CODE:004013AF                 push    offset aNoLuck  ; "No luck!"
CODE:004013B4                 push    offset aNoLuckThereMat ; "No luck there, mate!"
CODE:004013B9                 push    dword ptr [ebp+8]
CODE:004013BC                 call    MessageBoxA
CODE:004013C1
CODE:004013C1 locret_4013C1:                          ; CODE XREF: sub_40137E+2C↑j
CODE:004013C1                 retn
CODE:004013C1 sub_40137E      endp
CODE:004013C1
CODE:004013C2
CODE:004013C2 ; =============== S U B R O U T I N E =======================================
CODE:004013C2
CODE:004013C2
CODE:004013C2 sub_4013C2      proc near               ; CODE XREF: sub_40137E+1F↑p
CODE:004013C2                 xor     edi, edi
CODE:004013C4                 xor     ebx, ebx
CODE:004013C6
CODE:004013C6 loc_4013C6:                             ; CODE XREF: sub_4013C2+D↓j
CODE:004013C6                 mov     bl, [esi]
CODE:004013C8                 test    bl, bl
CODE:004013CA                 jz      short locret_4013D1
CODE:004013CC                 add     edi, ebx
CODE:004013CE                 inc     esi
CODE:004013CF                 jmp     short loc_4013C6
CODE:004013D1 ; ---------------------------------------------------------------------------
CODE:004013D1
CODE:004013D1 locret_4013D1:                          ; CODE XREF: sub_4013C2+8↑j
CODE:004013D1                 retn
CODE:004013D1 sub_4013C2      endp
CODE:004013D1
CODE:004013D2
CODE:004013D2 ; =============== S U B R O U T I N E =======================================
CODE:004013D2
CODE:004013D2
CODE:004013D2 sub_4013D2      proc near               ; CODE XREF: sub_40137E:loc_401394↑p
CODE:004013D2                 sub     al, 20h ; ' '
CODE:004013D4                 mov     [esi], al
CODE:004013D6                 retn
CODE:004013D6 sub_4013D2      endp
CODE:004013D6
CODE:004013D7 ; ---------------------------------------------------------------------------
CODE:004013D7                 retn
CODE:004013D8
CODE:004013D8 ; =============== S U B R O U T I N E =======================================
CODE:004013D8
CODE:004013D8
CODE:004013D8 sub_4013D8      proc near               ; CODE XREF: WndProc+110↑p
CODE:004013D8
CODE:004013D8 arg_0           = dword ptr  4
CODE:004013D8
CODE:004013D8                 xor     eax, eax
CODE:004013DA                 xor     edi, edi
CODE:004013DC                 xor     ebx, ebx
CODE:004013DE                 mov     esi, [esp+arg_0]
CODE:004013E2
CODE:004013E2 loc_4013E2:                             ; CODE XREF: sub_4013D8+1B↓j
CODE:004013E2                 mov     al, 0Ah
CODE:004013E4                 mov     bl, [esi]
CODE:004013E6                 test    bl, bl
CODE:004013E8                 jz      short loc_4013F5
CODE:004013EA                 sub     bl, 30h ; '0'
CODE:004013ED                 imul    edi, eax
CODE:004013F0                 add     edi, ebx
CODE:004013F2                 inc     esi
CODE:004013F3                 jmp     short loc_4013E2
CODE:004013F5 ; ---------------------------------------------------------------------------
CODE:004013F5
CODE:004013F5 loc_4013F5:                             ; CODE XREF: sub_4013D8+10↑j
CODE:004013F5                 xor     edi, 1234h
CODE:004013FB                 mov     ebx, edi
CODE:004013FD                 retn
CODE:004013FD sub_4013D8      endp
CODE:004013FD
CODE:004013FE ; ---------------------------------------------------------------------------
CODE:004013FE                 jmp     ds:KillTimer
CODE:00401404 ; ---------------------------------------------------------------------------
CODE:00401404                 jmp     ds:GetSystemMetrics
CODE:0040140A ; [00000006 BYTES: COLLAPSED FUNCTION LoadCursorA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:00401410 ; ---------------------------------------------------------------------------
CODE:00401410                 jmp     ds:LoadAcceleratorsA
CODE:00401416 ; [00000006 BYTES: COLLAPSED FUNCTION MessageBeep. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:0040141C ; ---------------------------------------------------------------------------
CODE:0040141C                 jmp     ds:GetWindowRect
CODE:00401422 ; ---------------------------------------------------------------------------
CODE:00401422                 jmp     ds:LoadStringA
CODE:00401428 ; [00000006 BYTES: COLLAPSED FUNCTION LoadIconA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:0040142E ; ---------------------------------------------------------------------------
CODE:0040142E                 jmp     ds:LoadBitmapA
CODE:00401434 ; [00000006 BYTES: COLLAPSED FUNCTION SetFocus. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:0040143A ; [00000006 BYTES: COLLAPSED FUNCTION MessageBoxA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:00401440 ; [00000006 BYTES: COLLAPSED FUNCTION PostQuitMessage. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:00401446 ; ---------------------------------------------------------------------------
CODE:00401446                 jmp     ds:WinHelpA
CODE:0040144C ; [00000006 BYTES: COLLAPSED FUNCTION InvalidateRect. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:00401452 ; ---------------------------------------------------------------------------
CODE:00401452                 jmp     ds:TranslateAcceleratorA
CODE:00401458 ; ---------------------------------------------------------------------------
CODE:00401458                 jmp     ds:MoveWindow
CODE:0040145E ; [00000006 BYTES: COLLAPSED FUNCTION TranslateMessage. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:00401464 ; ---------------------------------------------------------------------------
CODE:00401464                 jmp     ds:LoadMenuA
CODE:0040146A ; [00000006 BYTES: COLLAPSED FUNCTION ShowWindow. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:00401470 ; ---------------------------------------------------------------------------
CODE:00401470                 jmp     ds:SendMessageA
CODE:00401476 ; ---------------------------------------------------------------------------
CODE:00401476                 jmp     ds:SetTimer
CODE:0040147C ; ---------------------------------------------------------------------------
CODE:0040147C                 jmp     ds:SetWindowPos
CODE:00401482 ; [00000006 BYTES: COLLAPSED FUNCTION UpdateWindow. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:00401488 ; [00000006 BYTES: COLLAPSED FUNCTION RegisterClassA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:0040148E ; ---------------------------------------------------------------------------
CODE:0040148E                 jmp     ds:BeginPaint
CODE:00401494 ; [00000006 BYTES: COLLAPSED FUNCTION CreateWindowExA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:0040149A ; [00000006 BYTES: COLLAPSED FUNCTION DefWindowProcA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:004014A0 ; [00000006 BYTES: COLLAPSED FUNCTION DialogBoxParamA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:004014A6 ; [00000006 BYTES: COLLAPSED FUNCTION DispatchMessageA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:004014AC ; ---------------------------------------------------------------------------
CODE:004014AC                 jmp     ds:DrawMenuBar
CODE:004014B2 ; [00000006 BYTES: COLLAPSED FUNCTION EndDialog. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:004014B8 ; ---------------------------------------------------------------------------
CODE:004014B8                 jmp     ds:EndPaint
CODE:004014BE ; [00000006 BYTES: COLLAPSED FUNCTION FindWindowA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:004014C4 ; ---------------------------------------------------------------------------
CODE:004014C4                 jmp     ds:GetDC
CODE:004014CA ; ---------------------------------------------------------------------------
CODE:004014CA                 jmp     ds:GetDlgItem
CODE:004014D0 ; [00000006 BYTES: COLLAPSED FUNCTION GetDlgItemTextA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:004014D6 ; [00000006 BYTES: COLLAPSED FUNCTION GetMessageA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:004014DC ; ---------------------------------------------------------------------------
CODE:004014DC                 jmp     ds:GetLocalTime
CODE:004014E2 ; ---------------------------------------------------------------------------
CODE:004014E2                 jmp     ds:OpenFile
CODE:004014E8 ; ---------------------------------------------------------------------------
CODE:004014E8                 jmp     ds:GlobalFree
CODE:004014EE ; ---------------------------------------------------------------------------
CODE:004014EE                 jmp     ds:GlobalAlloc
CODE:004014F4 ; ---------------------------------------------------------------------------
CODE:004014F4                 jmp     ds:lstrlen
CODE:004014FA ; ---------------------------------------------------------------------------
CODE:004014FA                 jmp     ds:CloseHandle
CODE:00401500 ; ---------------------------------------------------------------------------
CODE:00401500                 jmp     ds:WriteFile
CODE:00401506 ; [00000006 BYTES: COLLAPSED FUNCTION GetModuleHandleA. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:0040150C ; ---------------------------------------------------------------------------
CODE:0040150C                 jmp     ds:ReadFile
CODE:00401512 ; [00000006 BYTES: COLLAPSED FUNCTION ExitProcess. PRESS CTRL-NUMPAD+ TO EXPAND]
CODE:00401518 ; ---------------------------------------------------------------------------
CODE:00401518                 jmp     ds:InitCommonControls
CODE:0040151E ; ---------------------------------------------------------------------------
CODE:0040151E                 jmp     ds:CreateToolbarEx
CODE:00401524 ; ---------------------------------------------------------------------------
CODE:00401524                 jmp     ds:CreateToolbar
CODE:0040152A ; ---------------------------------------------------------------------------
CODE:0040152A                 jmp     ds:TextOutA
CODE:00401530 ; ---------------------------------------------------------------------------
CODE:00401530                 jmp     ds:StartPage
CODE:00401536 ; ---------------------------------------------------------------------------
CODE:00401536                 jmp     ds:StartDocA
CODE:0040153C ; ---------------------------------------------------------------------------
CODE:0040153C                 jmp     ds:GetTextMetricsA
CODE:00401542 ; ---------------------------------------------------------------------------
CODE:00401542                 jmp     ds:GetStockObject
CODE:00401548 ; ---------------------------------------------------------------------------
CODE:00401548                 jmp     ds:EndPage
CODE:0040154E ; ---------------------------------------------------------------------------
CODE:0040154E                 jmp     ds:EndDoc
CODE:00401554 ; ---------------------------------------------------------------------------
CODE:00401554                 jmp     ds:DeleteObject
CODE:0040155A ; ---------------------------------------------------------------------------
CODE:0040155A                 jmp     ds:DeleteDC
CODE:00401560 ; ---------------------------------------------------------------------------
CODE:00401560                 jmp     ds:GetSaveFileNameA
CODE:00401566 ; ---------------------------------------------------------------------------
CODE:00401566                 jmp     ds:GetOpenFileNameA
CODE:0040156C ; ---------------------------------------------------------------------------
CODE:0040156C                 jmp     ds:PrintDlgA
CODE:0040156C ; ---------------------------------------------------------------------------
CODE:00401572                 align 100h
CODE:00401600                 dd 280h dup(?)
CODE:00401600 CODE            ends
CODE:00401600
DATA:00402000 ; Section 2. (virtual address 00002000)
DATA:00402000 ; Virtual size                  : 00001000 (   4096.)
DATA:00402000 ; Section size in file          : 00000200 (    512.)
DATA:00402000 ; Offset to raw data for section: 00000C00
DATA:00402000 ; Flags C0000040: Data Readable Writable
DATA:00402000 ; Alignment     : default
DATA:00402000 ; ===========================================================================
DATA:00402000
DATA:00402000 ; Segment type: Pure data
DATA:00402000 ; Segment permissions: Read/Write
DATA:00402000 DATA            segment para public 'DATA' use32
DATA:00402000                 assume cs:DATA
DATA:00402000                 ;org 402000h
DATA:00402000                 db    0
DATA:00402001                 db    0
DATA:00402002                 db    0
DATA:00402003                 db    0
DATA:00402004 dword_402004    dd 0                    ; DATA XREF: start+C8↑w
DATA:00402004                                         ; start+CF↑r ...
DATA:00402008                 db    0
DATA:00402009                 db    0
DATA:0040200A                 db    0
DATA:0040200B                 db    0
DATA:0040200C                 db    0
DATA:0040200D                 db    0
DATA:0040200E                 db    0
DATA:0040200F                 db    0
DATA:00402010                 db    0
DATA:00402011                 db    0
DATA:00402012                 db    0
DATA:00402013                 db    0
DATA:00402014                 db    0
DATA:00402015                 db    0
DATA:00402016                 db    0
DATA:00402017                 db    0
DATA:00402018                 db    0
DATA:00402019                 db    0
DATA:0040201A                 db    0
DATA:0040201B                 db    0
DATA:0040201C                 db    0
DATA:0040201D                 db    0
DATA:0040201E                 db    0
DATA:0040201F                 db    0
DATA:00402020                 db    0
DATA:00402021                 db    0
DATA:00402022                 db    0
DATA:00402023                 db    0
DATA:00402024                 db    0
DATA:00402025                 db    0
DATA:00402026                 db    0
DATA:00402027                 db    0
DATA:00402028                 db    0
DATA:00402029                 db    0
DATA:0040202A                 db    0
DATA:0040202B                 db    0
DATA:0040202C                 db    0
DATA:0040202D                 db    0
DATA:0040202E                 db    0
DATA:0040202F                 db    0
DATA:00402030                 db    0
DATA:00402031                 db    0
DATA:00402032                 db    0
DATA:00402033                 db    0
DATA:00402034                 db    0
DATA:00402035                 db    0
DATA:00402036                 db    0
DATA:00402037                 db    0
DATA:00402038                 db    0
DATA:00402039                 db    0
DATA:0040203A                 db    0
DATA:0040203B                 db    0
DATA:0040203C                 db    0
DATA:0040203D                 db    0
DATA:0040203E                 db    0
DATA:0040203F                 db    0
DATA:00402040                 db    0
DATA:00402041                 db    0
DATA:00402042                 db    0
DATA:00402043                 db    0
DATA:00402044                 db    0
DATA:00402045                 db    0
DATA:00402046                 db    0
DATA:00402047                 db    0
DATA:00402048 unk_402048      db    0                 ; DATA XREF: start+F7↑o
DATA:00402048                                         ; start+107↑o ...
DATA:00402049                 db    0
DATA:0040204A                 db    0
DATA:0040204B                 db    0
DATA:0040204C                 db    0
DATA:0040204D                 db    0
DATA:0040204E                 db    0
DATA:0040204F                 db    0
DATA:00402050 dword_402050    dd 0                    ; DATA XREF: start:loc_40111D↑r
DATA:00402054                 db    0
DATA:00402055                 db    0
DATA:00402056                 db    0
DATA:00402057                 db    0
DATA:00402058                 db    0
DATA:00402059                 db    0
DATA:0040205A                 db    0
DATA:0040205B                 db    0
DATA:0040205C                 db    0
DATA:0040205D                 db    0
DATA:0040205E                 db    0
DATA:0040205F                 db    0
DATA:00402060                 db    0
DATA:00402061                 db    0
DATA:00402062                 db    0
DATA:00402063                 db    0
DATA:00402064 dword_402064    dd 0                    ; DATA XREF: start:loc_40101D↑w
DATA:00402064                                         ; start+8B↑o
DATA:00402068 dword_402068    dd 0                    ; DATA XREF: start+27↑w
DATA:0040206C dword_40206C    dd 0                    ; DATA XREF: start+31↑w
DATA:00402070 dword_402070    dd 0                    ; DATA XREF: start+3B↑w
DATA:00402074 dword_402074    dd 0                    ; DATA XREF: start+4A↑w
DATA:00402078 dword_402078    dd 0                    ; DATA XREF: start+57↑w
DATA:0040207C dword_40207C    dd 0                    ; DATA XREF: start+68↑w
DATA:00402080 dword_402080    dd 0                    ; DATA XREF: start+6D↑w
DATA:00402084 dword_402084    dd 0                    ; DATA XREF: start+77↑w
DATA:00402088 dword_402088    dd 0                    ; DATA XREF: start+81↑w
DATA:0040208C                 db    0
DATA:0040208D                 db    0
DATA:0040208E                 db    0
DATA:0040208F                 db    0
DATA:00402090                 db    0
DATA:00402091                 db    0
DATA:00402092                 db    0
DATA:00402093                 db    0
DATA:00402094                 db    0
DATA:00402095                 db    0
DATA:00402096                 db    0
DATA:00402097                 db    0
DATA:00402098                 db    0
DATA:00402099                 db    0
DATA:0040209A                 db    0
DATA:0040209B                 db    0
DATA:0040209C                 db    0
DATA:0040209D                 db    0
DATA:0040209E                 db    0
DATA:0040209F                 db    0
DATA:004020A0                 db    0
DATA:004020A1                 db    0
DATA:004020A2                 db    0
DATA:004020A3                 db    0
DATA:004020A4                 db    0
DATA:004020A5                 db    0
DATA:004020A6                 db    0
DATA:004020A7                 db    0
DATA:004020A8                 db    0
DATA:004020A9                 db    0
DATA:004020AA                 db    0
DATA:004020AB                 db    0
DATA:004020AC                 db    0
DATA:004020AD                 db    0
DATA:004020AE                 db    0
DATA:004020AF                 db    0
DATA:004020B0                 db    0
DATA:004020B1                 db    0
DATA:004020B2                 db    0
DATA:004020B3                 db    0
DATA:004020B4                 db    0
DATA:004020B5                 db    0
DATA:004020B6                 db    0
DATA:004020B7                 db    0
DATA:004020B8                 db    0
DATA:004020B9                 db    0
DATA:004020BA                 db    0
DATA:004020BB                 db    0
DATA:004020BC                 db    0
DATA:004020BD                 db    0
DATA:004020BE                 db    0
DATA:004020BF                 db    0
DATA:004020C0                 db    0
DATA:004020C1                 db    0
DATA:004020C2                 db    0
DATA:004020C3                 db    0
DATA:004020C4                 db    0
DATA:004020C5                 db    0
DATA:004020C6                 db    0
DATA:004020C7                 db    0
DATA:004020C8                 db    0
DATA:004020C9                 db    0
DATA:004020CA dword_4020CA    dd 0                    ; DATA XREF: start+7↑w
DATA:004020CA                                         ; start+45↑r ...
DATA:004020CE                 db    0
DATA:004020CF                 db    0
DATA:004020D0                 db    0
DATA:004020D1                 db    0
DATA:004020D2                 db    0
DATA:004020D3                 db    0
DATA:004020D4                 db    0
DATA:004020D5                 db    0
DATA:004020D6                 db  54h ; T
DATA:004020D7                 db  72h ; r
DATA:004020D8                 db  79h ; y
DATA:004020D9                 db  20h
DATA:004020DA                 db  74h ; t
DATA:004020DB                 db  6Fh ; o
DATA:004020DC                 db  20h
DATA:004020DD                 db  63h ; c
DATA:004020DE                 db  72h ; r
DATA:004020DF                 db  61h ; a
DATA:004020E0                 db  63h ; c
DATA:004020E1                 db  6Bh ; k
DATA:004020E2                 db  20h
DATA:004020E3                 db  6Dh ; m
DATA:004020E4                 db  65h ; e
DATA:004020E5                 db  21h ; !
DATA:004020E6                 db    0
DATA:004020E7 aCrackmeV10     db 'CrackMe v1.0',0     ; DATA XREF: start+B7↑o
DATA:004020F4 aNoNeedToDisasm db 'No need to disasm the code!',0
DATA:004020F4                                         ; DATA XREF: start+E↑o
DATA:004020F4                                         ; start+81↑o ...
DATA:00402110 aMenu           db 'MENU',0             ; DATA XREF: start+77↑o
DATA:00402115 aDlgRegis       db 'DLG_REGIS',0        ; DATA XREF: WndProc+EB↑o
DATA:0040211F aDlgAbout       db 'DLG_ABOUT',0        ; DATA XREF: WndProc+CF↑o
DATA:00402129 aGoodWork       db 'Good work!',0       ; DATA XREF: sub_40134D+2↑o
DATA:00402134 aGreatWorkMateN db 'Great work, mate!',0Dh,'Now try the next CrackMe!',0
DATA:00402134                                         ; DATA XREF: sub_40134D+7↑o
DATA:00402160 aNoLuck         db 'No luck!',0         ; DATA XREF: sub_401362+9↑o
DATA:00402160                                         ; sub_40137E+31↑o
DATA:00402169 aNoLuckThereMat db 'No luck there, mate!',0
DATA:00402169                                         ; DATA XREF: sub_401362+E↑o
DATA:00402169                                         ; sub_40137E+36↑o
DATA:0040217E unk_40217E      db    0                 ; DATA XREF: WndProc+10B↑o
DATA:0040217E                                         ; sub_401253+84↑o
DATA:0040217F                 db    0
DATA:00402180                 db    0
DATA:00402181                 db    0
DATA:00402182                 db    0
DATA:00402183                 db    0
DATA:00402184                 db    0
DATA:00402185                 db    0
DATA:00402186                 db    0
DATA:00402187                 db    0
DATA:00402188                 db    0
DATA:00402189                 db    0
DATA:0040218A                 db    0
DATA:0040218B                 db    0
DATA:0040218C                 db    0
DATA:0040218D                 db    0
DATA:0040218E unk_40218E      db    0                 ; DATA XREF: WndProc+100↑o
DATA:0040218E                                         ; sub_401253+64↑o
DATA:0040218F                 db    0
DATA:00402190                 db    0
DATA:00402191                 db    0
DATA:00402192                 db    0
DATA:00402193                 db    0
DATA:00402194                 db    0
DATA:00402195                 db    0
DATA:00402196                 db    0
DATA:00402197                 db    0
DATA:00402198                 db    0
DATA:00402199                 db    0
DATA:0040219A                 db    0
DATA:0040219B                 db    0
DATA:0040219C                 db    0
DATA:0040219D                 db    0
DATA:0040219E                 db    0
DATA:0040219F                 db    0
DATA:004021A0                 db    0
DATA:004021A1                 db    0
DATA:004021A2                 db    0
DATA:004021A3                 db    0
DATA:004021A4                 db    0
DATA:004021A5                 db    0
DATA:004021A6                 db    0
DATA:004021A7                 db    0
DATA:004021A8                 db    0
DATA:004021A9                 db    0
DATA:004021AA                 db    0
DATA:004021AB                 db    0
DATA:004021AC                 db    0
DATA:004021AD                 db    0
DATA:004021AE                 db    0
DATA:004021AF                 db    0
DATA:004021B0                 db    0
DATA:004021B1                 db    0
DATA:004021B2                 db    0
DATA:004021B3                 db    0
DATA:004021B4                 db    0
DATA:004021B5                 db    0
DATA:004021B6                 db    0
DATA:004021B7                 db    0
DATA:004021B8                 db    0
DATA:004021B9                 db    0
DATA:004021BA                 db    0
DATA:004021BB                 db    0
DATA:004021BC                 db    0
DATA:004021BD                 db    0
DATA:004021BE                 db    0
DATA:004021BF                 db    0
DATA:004021C0                 db    0
DATA:004021C1                 db    0
DATA:004021C2                 db    0
DATA:004021C3                 db    0
DATA:004021C4                 db    0
DATA:004021C5                 db    0
DATA:004021C6                 db    0
DATA:004021C7                 db    0
DATA:004021C8                 db    0
DATA:004021C9                 db    0
DATA:004021CA                 db    0
DATA:004021CB                 db    0
DATA:004021CC                 db    0
DATA:004021CD                 db    0
DATA:004021CE                 db    0
DATA:004021CF                 db    0
DATA:004021D0                 db    0
DATA:004021D1                 db    0
DATA:004021D2                 db    0
DATA:004021D3                 db    0
DATA:004021D4                 db    0
DATA:004021D5                 db    0
DATA:004021D6                 db    0
DATA:004021D7                 db    0
DATA:004021D8                 db    0
DATA:004021D9                 db    0
DATA:004021DA                 db    0
DATA:004021DB                 db    0
DATA:004021DC                 db    0
DATA:004021DD                 db    0
DATA:004021DE                 db    0
DATA:004021DF                 db    0
DATA:004021E0                 db    0
DATA:004021E1                 db    0
DATA:004021E2                 db    0
DATA:004021E3                 db    0
DATA:004021E4                 db    0
DATA:004021E5                 db    0
DATA:004021E6                 db    0
DATA:004021E7                 db    0
DATA:004021E8                 db    0
DATA:004021E9                 db    0
DATA:004021EA                 db    0
DATA:004021EB                 db    0
DATA:004021EC                 db    0
DATA:004021ED                 db    0
DATA:004021EE                 db    0
DATA:004021EF                 db    0
DATA:004021F0                 db    0
DATA:004021F1                 db    0
DATA:004021F2                 db    0
DATA:004021F3                 db    0
DATA:004021F4                 db    0
DATA:004021F5                 db    0
DATA:004021F6                 db    0
DATA:004021F7                 db    0
DATA:004021F8                 db    0
DATA:004021F9                 db    0
DATA:004021FA                 db    0
DATA:004021FB                 db    0
DATA:004021FC                 db    0
DATA:004021FD                 db    0
DATA:004021FE                 db    0
DATA:004021FF                 db    0
DATA:00402200                 align 1000h
DATA:00402200 DATA            ends
DATA:00402200
.idata:00403000 ; Section 3. (virtual address 00003000)
.idata:00403000 ; Virtual size                  : 00001000 (   4096.)
.idata:00403000 ; Section size in file          : 00000800 (   2048.)
.idata:00403000 ; Offset to raw data for section: 00000E00
.idata:00403000 ; Flags C0000040: Data Readable Writable
.idata:00403000 ; Alignment     : default
.idata:00403000 ; ===========================================================================
.idata:00403000
.idata:00403000 ; Segment type: Externs
.idata:00403000 ; _idata
.idata:00403000
.idata:00403001
.idata:00403184 ;
.idata:00403184 ; Imports from USER32.dll
.idata:00403184 ;
.idata:00403184                 extrn KillTimer:dword   ; DATA XREF: CODE:004013FE↑r
.idata:00403188                 extrn GetSystemMetrics:dword
.idata:00403188                                         ; DATA XREF: CODE:00401404↑r
.idata:0040318C                 extrn __imp_LoadCursorA:dword
.idata:0040318C                                         ; DATA XREF: LoadCursorA↑r
.idata:00403190                 extrn LoadAcceleratorsA:dword
.idata:00403190                                         ; DATA XREF: CODE:00401410↑r
.idata:00403194                 extrn __imp_MessageBeep:dword
.idata:00403194                                         ; DATA XREF: MessageBeep↑r
.idata:00403198                 extrn GetWindowRect:dword
.idata:00403198                                         ; DATA XREF: CODE:0040141C↑r
.idata:0040319C                 extrn LoadStringA:dword ; DATA XREF: CODE:00401422↑r
.idata:004031A0                 extrn __imp_LoadIconA:dword
.idata:004031A0                                         ; DATA XREF: LoadIconA↑r
.idata:004031A4                 extrn LoadBitmapA:dword ; DATA XREF: CODE:0040142E↑r
.idata:004031A8                 extrn __imp_SetFocus:dword
.idata:004031A8                                         ; DATA XREF: SetFocus↑r
.idata:004031AC                 extrn __imp_MessageBoxA:dword
.idata:004031AC                                         ; DATA XREF: MessageBoxA↑r
.idata:004031B0                 extrn __imp_PostQuitMessage:dword
.idata:004031B0                                         ; DATA XREF: PostQuitMessage↑r
.idata:004031B4                 extrn WinHelpA:dword    ; DATA XREF: CODE:00401446↑r
.idata:004031B8                 extrn __imp_InvalidateRect:dword
.idata:004031B8                                         ; DATA XREF: InvalidateRect↑r
.idata:004031BC                 extrn TranslateAcceleratorA:dword
.idata:004031BC                                         ; DATA XREF: CODE:00401452↑r
.idata:004031C0                 extrn MoveWindow:dword  ; DATA XREF: CODE:00401458↑r
.idata:004031C4                 extrn __imp_TranslateMessage:dword
.idata:004031C4                                         ; DATA XREF: TranslateMessage↑r
.idata:004031C8                 extrn LoadMenuA:dword   ; DATA XREF: CODE:00401464↑r
.idata:004031CC                 extrn __imp_ShowWindow:dword
.idata:004031CC                                         ; DATA XREF: ShowWindow↑r
.idata:004031D0                 extrn SendMessageA:dword
.idata:004031D0                                         ; DATA XREF: CODE:00401470↑r
.idata:004031D4                 extrn SetTimer:dword    ; DATA XREF: CODE:00401476↑r
.idata:004031D8                 extrn SetWindowPos:dword
.idata:004031D8                                         ; DATA XREF: CODE:0040147C↑r
.idata:004031DC                 extrn __imp_UpdateWindow:dword
.idata:004031DC                                         ; DATA XREF: UpdateWindow↑r
.idata:004031E0                 extrn __imp_RegisterClassA:dword
.idata:004031E0                                         ; DATA XREF: RegisterClassA↑r
.idata:004031E4                 extrn BeginPaint:dword  ; DATA XREF: CODE:0040148E↑r
.idata:004031E8                 extrn __imp_CreateWindowExA:dword
.idata:004031E8                                         ; DATA XREF: CreateWindowExA↑r
.idata:004031EC                 extrn __imp_DefWindowProcA:dword
.idata:004031EC                                         ; DATA XREF: DefWindowProcA↑r
.idata:004031F0                 extrn __imp_DialogBoxParamA:dword
.idata:004031F0                                         ; DATA XREF: DialogBoxParamA↑r
.idata:004031F4                 extrn __imp_DispatchMessageA:dword
.idata:004031F4                                         ; DATA XREF: DispatchMessageA↑r
.idata:004031F8                 extrn DrawMenuBar:dword ; DATA XREF: CODE:004014AC↑r
.idata:004031FC                 extrn __imp_EndDialog:dword
.idata:004031FC                                         ; DATA XREF: EndDialog↑r
.idata:00403200                 extrn EndPaint:dword    ; DATA XREF: CODE:004014B8↑r
.idata:00403204                 extrn __imp_FindWindowA:dword
.idata:00403204                                         ; DATA XREF: FindWindowA↑r
.idata:00403208                 extrn GetDC:dword       ; DATA XREF: CODE:004014C4↑r
.idata:0040320C                 extrn GetDlgItem:dword  ; DATA XREF: CODE:004014CA↑r
.idata:00403210                 extrn __imp_GetDlgItemTextA:dword
.idata:00403210                                         ; DATA XREF: GetDlgItemTextA↑r
.idata:00403214                 extrn __imp_GetMessageA:dword
.idata:00403214                                         ; DATA XREF: GetMessageA↑r
.idata:00403218
.idata:0040321C ;
.idata:0040321C ; Imports from KERNEL32.dll
.idata:0040321C ;
.idata:0040321C                 extrn GetLocalTime:dword
.idata:0040321C                                         ; DATA XREF: CODE:004014DC↑r
.idata:00403220                 extrn OpenFile:dword    ; DATA XREF: CODE:004014E2↑r
.idata:00403224                 extrn GlobalFree:dword  ; DATA XREF: CODE:004014E8↑r
.idata:00403228                 extrn GlobalAlloc:dword ; DATA XREF: CODE:004014EE↑r
.idata:0040322C                 extrn lstrlen:dword     ; DATA XREF: CODE:004014F4↑r
.idata:00403230                 extrn CloseHandle:dword ; DATA XREF: CODE:004014FA↑r
.idata:00403234                 extrn WriteFile:dword   ; DATA XREF: CODE:00401500↑r
.idata:00403238                 extrn __imp_GetModuleHandleA:dword
.idata:00403238                                         ; DATA XREF: GetModuleHandleA↑r
.idata:0040323C                 extrn ReadFile:dword    ; DATA XREF: CODE:0040150C↑r
.idata:00403240                 extrn __imp_ExitProcess:dword
.idata:00403240                                         ; DATA XREF: ExitProcess↑r
.idata:00403244
.idata:00403248 ;
.idata:00403248 ; Imports from COMCTL32.DLL
.idata:00403248 ;
.idata:00403248                 extrn InitCommonControls:dword
.idata:00403248                                         ; DATA XREF: CODE:00401518↑r
.idata:0040324C                 extrn CreateToolbarEx:dword
.idata:0040324C                                         ; DATA XREF: CODE:0040151E↑r
.idata:00403250                 extrn CreateToolbar:dword
.idata:00403250                                         ; DATA XREF: CODE:00401524↑r
.idata:00403254
.idata:00403258 ;
.idata:00403258 ; Imports from GDI32.dll
.idata:00403258 ;
.idata:00403258                 extrn TextOutA:dword    ; DATA XREF: CODE:0040152A↑r
.idata:0040325C                 extrn StartPage:dword   ; DATA XREF: CODE:00401530↑r
.idata:00403260                 extrn StartDocA:dword   ; DATA XREF: CODE:00401536↑r
.idata:00403264                 extrn GetTextMetricsA:dword
.idata:00403264                                         ; DATA XREF: CODE:0040153C↑r
.idata:00403268                 extrn GetStockObject:dword
.idata:00403268                                         ; DATA XREF: CODE:00401542↑r
.idata:0040326C                 extrn EndPage:dword     ; DATA XREF: CODE:00401548↑r
.idata:00403270                 extrn EndDoc:dword      ; DATA XREF: CODE:0040154E↑r
.idata:00403274                 extrn DeleteObject:dword
.idata:00403274                                         ; DATA XREF: CODE:00401554↑r
.idata:00403278                 extrn DeleteDC:dword    ; DATA XREF: CODE:0040155A↑r
.idata:0040327C
.idata:00403280 ;
.idata:00403280 ; Imports from COMDLG32.dll
.idata:00403280 ;
.idata:00403280                 extrn GetSaveFileNameA:dword
.idata:00403280                                         ; DATA XREF: CODE:00401560↑r
.idata:00403284                 extrn GetOpenFileNameA:dword
.idata:00403284                                         ; DATA XREF: CODE:00401566↑r
.idata:00403288                 extrn PrintDlgA:dword   ; DATA XREF: CODE:0040156C↑r
.idata:0040328C
.idata:0040328C
.idata:0040328C
.idata:0040328C                 end start